INSERT INTO rss_feeds (feed_url, publisher, label, category_hint, locale_hint, is_enabled, tone_risk_score)
VALUES
  ('https://www.npr.org/rss/rss.php?id=1001', 'NPR', 'National', 'Community Heroes', 'US', TRUE, 3),
  ('https://www.npr.org/rss/rss.php?id=2', 'NPR', 'News', 'Human Kindness', 'US', TRUE, 3),
  ('https://www.sciencedaily.com/rss/all.xml', 'ScienceDaily', 'All Headlines', 'Science & Discovery', 'global', TRUE, 3),
  ('https://www.sciencedaily.com/rss/plants_animals.xml', 'ScienceDaily', 'Plants & Animals', 'Environment & Nature', 'global', TRUE, 2),
  ('https://www.sciencedaily.com/rss/health_medicine.xml', 'ScienceDaily', 'Health & Medicine', 'Health & Wellness', 'global', TRUE, 2),
  ('https://www.sciencedaily.com/rss/computers_math.xml', 'ScienceDaily', 'Computers & Math', 'Innovation & Tech', 'global', TRUE, 2),
  ('https://www.sciencedaily.com/rss/top/environment.xml', 'ScienceDaily', 'Environment Top', 'Environment & Nature', 'global', TRUE, 2),
  ('https://www.sciencedaily.com/rss/top/health.xml', 'ScienceDaily', 'Health Top', 'Health & Wellness', 'global', TRUE, 2),
  ('https://www.sciencedaily.com/rss/top/science.xml', 'ScienceDaily', 'Science Top', 'Science & Discovery', 'global', TRUE, 2),
  ('https://www.eurekalert.org/rss.xml', 'EurekAlert!', 'Research News', 'Science & Discovery', 'global', TRUE, 3),
  ('https://earthobservatory.nasa.gov/feeds/image-of-the-day.rss', 'NASA Earth Observatory', 'Image of the Day', 'Environment & Nature', 'global', TRUE, 2),
  ('https://www.nasa.gov/rss/dyn/lg_image_of_the_day.rss', 'NASA', 'Image of the Day', 'Science & Discovery', 'US', TRUE, 2),
  ('https://www.esa.int/rssfeed/Our_Activities/Space_Science', 'ESA', 'Space Science', 'Science & Discovery', 'global', TRUE, 2),
  ('https://www.nature.com/nature.rss', 'Nature', 'Nature Research', 'Science & Discovery', 'global', TRUE, 3),
  ('https://www.weforum.org/agenda/feed/', 'World Economic Forum', 'Agenda', 'Innovation & Tech', 'global', TRUE, 4),
  ('https://www.weforum.org/agenda/archive/future-of-health/feed/', 'World Economic Forum', 'Future of Health', 'Health & Wellness', 'global', TRUE, 4),
  ('https://www.weforum.org/agenda/archive/climate-action/feed/', 'World Economic Forum', 'Climate Action', 'Environment & Nature', 'global', TRUE, 4),
  ('https://www.edutopia.org/rss.xml', 'Edutopia', 'Latest', 'Education', 'US', TRUE, 2),
  ('https://www.ecowatch.com/feed', 'EcoWatch', 'Latest', 'Environment & Nature', 'US', TRUE, 4),
  ('https://www.usgs.gov/news/featured-story/feed', 'USGS', 'Featured Stories', 'Environment & Nature', 'US', TRUE, 2),
  ('https://www.unicef.org/rss.xml', 'UNICEF', 'News', 'Community Heroes', 'global', TRUE, 3),
  ('https://www.unesco.org/en/feeds/news', 'UNESCO', 'News', 'Education', 'global', TRUE, 3),
  ('https://www.doctorswithoutborders.org/latest/rss.xml', 'Doctors Without Borders', 'Latest', 'Community Heroes', 'global', TRUE, 4),
  ('https://www.redcross.org/about-us/news-and-events/news.rss', 'American Red Cross', 'News', 'Community Heroes', 'US', TRUE, 3),
  ('https://www.habitat.org/stories.rss', 'Habitat for Humanity', 'Stories', 'Human Kindness', 'global', TRUE, 3),
  ('https://www.si.edu/rss', 'Smithsonian Institution', 'Top Stories', 'Arts & Culture', 'US', TRUE, 3),
  ('https://www.metmuseum.org/rss/metmuseum', 'The Met', 'Museum News', 'Arts & Culture', 'US', TRUE, 2),
  ('https://www.moma.org/calendar/exhibitions.rss', 'MoMA', 'Exhibitions', 'Arts & Culture', 'US', TRUE, 3),
  ('https://www.nationalgeographic.com/content/natgeo/en_us/index.rss', 'National Geographic', 'Latest', 'Environment & Nature', 'global', TRUE, 3),
  ('https://www.goodnewsnetwork.org/feed/', 'Good News Network', 'Top Good News', 'Human Kindness', 'global', TRUE, 4),
  ('https://www.positive.news/feed/', 'Positive News', 'Latest', 'Human Kindness', 'global', TRUE, 3),
  ('https://www.optimistdaily.com/feed/', 'The Optimist Daily', 'Latest', 'Human Kindness', 'global', TRUE, 4),
  ('https://www.fastcompany.com/section/impact/rss', 'Fast Company', 'Impact', 'Innovation & Tech', 'US', TRUE, 4),
  ('https://www.fastcompany.com/section/work-life/rss', 'Fast Company', 'Work Life', 'Health & Wellness', 'US', TRUE, 4),
  ('https://www.mckinsey.com/featured-insights/rss', 'McKinsey', 'Featured Insights', 'Innovation & Tech', 'global', TRUE, 4),
  ('https://engineering.mit.edu/feed/', 'MIT School of Engineering', 'Latest', 'Innovation & Tech', 'US', TRUE, 2)
ON CONFLICT DO NOTHING;
